# Generated by Django 5.0.6 on 2024-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfilili', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
