# Generated by Django 5.0.6 on 2024-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfilili', '0003_detailregistration_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailregister',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
