# Generated by Django 5.0.6 on 2024-06-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfilili', '0004_alter_emailregister_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailregistration',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfilili.emailregister'),
        ),
    ]
